# Generated by Django 5.2.18 on 2026-10-09 03:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_number', models.CharField(max_length=30, unique=True)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=90)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('mileage', models.PositiveIntegerField(help_text='Odometer reading in kilometres.')),
                ('body', models.CharField(choices=[('Coupe', 'Coupe'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback')], max_length=20)),
                ('transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=20)),
                ('fuel', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=20)),
                ('colour', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=6000)),
                ('features', models.TextField(blank=True, help_text='One verified feature per line.', max_length=3000)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('archived', 'Archived')], db_index=True, default='draft', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('is_demo', models.BooleanField(default=False, help_text='Illustrative inventory. Excluded from production browsing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='nonnegative_price')],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('alt', models.CharField(help_text='Describe the vehicle and angle, e.g. front three-quarter view.', max_length=180)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inventory.vehicle')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(max_length=3000)),
                ('consent', models.BooleanField()),
                ('state', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('staff_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
