const {chromium}=require('playwright');
const {execFileSync,spawn}=require('node:child_process');
const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const assert=require('node:assert/strict');
(async()=>{
 const directory=await fs.mkdtemp(path.join(os.tmpdir(),'carhaven-browser-'));const python=process.env.PYTHON??'python';const password=crypto.randomBytes(24).toString('hex');const origin='http://127.0.0.1:8093';
 const env={...process.env,DATABASE_URL:'',ENVIRONMENT:'test',CLIENT_APPROVED:'0',SQLITE_PATH:path.join(directory,'db.sqlite3'),MEDIA_ROOT:path.join(directory,'photos'),SITE_ORIGIN:origin,SECRET_KEY:crypto.randomBytes(32).toString('hex'),QA_PASSWORD:password};
 const run=(args)=>execFileSync(python,args,{env,stdio:'pipe'});
 run(['manage.py','migrate','--noinput']);run(['manage.py','seed_demo']);run(['manage.py','collectstatic','--noinput']);run(['manage.py','shell','-c',"import os; from django.contrib.auth.models import User; User.objects.create_superuser('qaadmin','qa@example.test',os.environ['QA_PASSWORD'])"]);
 run(['-c',"from PIL import Image; import os; Image.new('RGB',(900,600),'#72886e').save(os.path.join(os.path.dirname(os.environ['SQLITE_PATH']),'test.jpg'))"]);
 const server=spawn(python,['manage.py','runserver','127.0.0.1:8093','--noreload'],{env,stdio:'ignore'});let browser,context;
 try{
  for(let i=0;i<100;i++){try{if((await fetch(origin+'/health/')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  browser=await chromium.launch({headless:true});context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:'evidence/video',size:{width:1280,height:900}}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await fs.mkdir('evidence',{recursive:true});await page.goto(origin);await page.getByRole('heading',{name:'The next chapter.'}).waitFor();await page.screenshot({path:'evidence/home-desktop.png',fullPage:true});
  await page.goto(origin+'/collection/');await page.getByLabel('Make',{exact:true}).selectOption('Porsche');await page.getByRole('button',{name:'Apply filters'}).click();assert.equal(await page.locator('.vehicle-card').count(),1);await page.getByRole('link',{name:'Explore 2023 Porsche'}).click();await page.getByRole('heading',{name:'Porsche'}).waitFor();await page.getByRole('link',{name:'Enquire about this vehicle'}).click();await page.locator('#id_name').fill('Fictional Buyer');await page.locator('#id_email').fill('buyer@example.test');await page.locator('#id_message').fill('Fictional viewing request for browser validation.');await page.locator('#id_consent').check();await page.getByRole('button',{name:'Send enquiry'}).click();await page.getByRole('heading',{name:'Thank you.'}).waitFor();
  await page.goto(origin+'/staff/');await page.getByLabel('Username:').fill('qaadmin');await page.getByLabel('Password:').fill(password);await page.getByRole('button',{name:'Log in'}).click();await page.getByRole('heading',{name:'Manage the collection'}).waitFor();
  await page.goto(origin+'/staff/inventory/vehicle/add/');await page.locator('#id_stock_number').fill('QA-VEHICLE');await page.locator('#id_make').fill('Example');await page.locator('#id_model').fill('Grand Tourer');await page.locator('#id_year').fill('2024');await page.locator('#id_price').fill('65000');await page.locator('#id_mileage').fill('12000');await page.locator('#id_body').selectOption('Coupe');await page.locator('#id_transmission').selectOption('Automatic');await page.locator('#id_fuel').selectOption('Petrol');await page.locator('#id_colour').fill('Silver');await page.locator('#id_description').fill('Fictional QA stock. Not for sale.');await page.getByRole('button',{name:'Save and continue editing'}).click();await page.locator('.success').waitFor();
  await page.locator('.add-row a').click();await page.locator('input[name="photos-0-image"]').setInputFiles(path.join(directory,'test.jpg'));await page.locator('input[name="photos-0-alt"]').fill('Fictional QA image, not an actual vehicle photograph');await page.getByRole('button',{name:'Save and continue editing'}).click();await page.locator('.success').waitFor();await page.locator('#id_state').selectOption('available');await page.getByRole('button',{name:'Save and continue editing'}).click();await page.locator('.success').waitFor();const editUrl=page.url();
  await page.goto(origin+'/collection/?q=Grand+Tourer');await page.getByRole('link',{name:'Explore 2024 Example'}).click();await page.getByRole('heading',{name:'Example'}).waitFor();assert.equal(await page.locator('.gallery img').count(),1);const detailUrl=page.url();
  await page.goto(editUrl);await page.locator('#id_state').selectOption('archived');await page.getByRole('button',{name:'Save and continue editing'}).click();await page.locator('.success').waitFor();assert.equal((await page.goto(detailUrl)).status(),404);
  await page.goto(origin+'/staff/inventory/enquiry/');await page.getByRole('link',{name:'Fictional Buyer'}).click();await page.locator('#id_state').selectOption('contacted');await page.locator('#id_staff_notes').fill('QA review only. No buyer contacted.');await page.getByRole('button',{name:'Save',exact:true}).click();await page.locator('.success').waitFor();
  await page.setViewportSize({width:390,height:844});await page.goto(origin);await page.screenshot({path:'evidence/home-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.getByRole('button',{name:'Toggle navigation'}).click();await page.locator('#navigation').getByRole('link',{name:'The collection'}).click();await page.screenshot({path:'evidence/collection-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(errors.length,0,errors.join('\n'));console.log('Browser passed: responsive public pages, filtering, enquiry, staff draft/photo/publish/archive and review.');
 }catch(e){if(context){const pages=context.pages();if(pages[0])await pages[0].screenshot({path:'evidence/failure.png',fullPage:true});}throw e;}finally{if(context)await context.close();if(browser)await browser.close();server.kill('SIGTERM');await new Promise(resolve=>server.once('exit',resolve));await fs.rm(directory,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
